"""Export a VoxelGrid as a Litematica .litematic schematic file.

Litematica schematics use NBT format with a specific schema. The existing
nbt.py writer handles all the binary encoding.
"""

from __future__ import annotations

import time
from pathlib import Path

from ..core.grid import VoxelGrid
from .nbt import (
    TAG_BYTE,
    TAG_COMPOUND,
    TAG_INT,
    TAG_LIST,
    TAG_LONG,
    TAG_SHORT,
    TAG_STRING,
    write_nbt_file,
)

# Litematica schema version
SCHEMA_VERSION = 6
# Minecraft data version for 1.21.x
DATA_VERSION = 3700


def export_litematic(
    grid: VoxelGrid,
    output: str | Path,
    origin: tuple[int, int, int] = (0, 0, 0),
    name: str = "GeoVox Export",
    author: str = "GeoVox",
) -> list[Path]:
    """Export a block grid as a Litematica .litematic schematic.

    Args:
        grid: VoxelGrid with Minecraft block name strings (post-palette).
        output: Output path (extension added automatically).
        origin: Offset applied to all coordinates.
        name: Schematic name stored in metadata.
        author: Author name stored in metadata.

    Returns:
        List of written file paths.
    """
    output = Path(output)
    output.parent.mkdir(parents=True, exist_ok=True)

    if not grid.cells:
        return []

    (x0, y0, z0), (x1, y1, z1) = grid.bounds()
    size_x = x1 - x0 + 1
    size_y = y1 - y0 + 1
    size_z = z1 - z0 + 1

    # Build palette: block name -> index (0 = air)
    palette_map: dict[str, int] = {"minecraft:air": 0}
    for block in grid.cells.values():
        if isinstance(block, str) and block not in palette_map:
            palette_map[block] = len(palette_map)

    # Build block state array as a flat list (XZY order per Litematica convention)
    volume = size_x * size_y * size_z
    block_states = _pack_block_states(grid, palette_map, x0, y0, z0, size_x, size_y, size_z)

    # Build palette NBT
    palette_nbt = {}
    for block_name, idx in palette_map.items():
        palette_nbt[block_name] = (TAG_COMPOUND, {
            "Name": (TAG_STRING, block_name),
        })

    # Region compound
    region_name = "GeoVox"
    region = {
        "Position": (TAG_COMPOUND, {
            "x": (TAG_INT, origin[0]),
            "y": (TAG_INT, origin[1]),
            "z": (TAG_INT, origin[2]),
        }),
        "Size": (TAG_COMPOUND, {
            "x": (TAG_INT, size_x),
            "y": (TAG_INT, size_y),
            "z": (TAG_INT, size_z),
        }),
        "BlockStatePalette": (TAG_LIST, (TAG_COMPOUND, [
            {"Name": (TAG_STRING, bname)} for bname, _ in sorted(palette_map.items(), key=lambda kv: kv[1])
        ])),
        "BlockStates": (TAG_LIST, (TAG_LONG, block_states)),
        "Entities": (TAG_LIST, (TAG_COMPOUND, [])),
        "TileEntities": (TAG_LIST, (TAG_COMPOUND, [])),
        "PendingBlockTicks": (TAG_LIST, (TAG_COMPOUND, [])),
        "PendingFluidTicks": (TAG_LIST, (TAG_COMPOUND, [])),
    }

    # Metadata
    now_ms = int(time.time() * 1000)
    metadata = {
        "Name": (TAG_STRING, name),
        "Author": (TAG_STRING, author),
        "Description": (TAG_STRING, f"Generated by GeoVox from {grid.metadata.get('source', 'unknown')}"),
        "TimeCreated": (TAG_LONG, now_ms),
        "TimeModified": (TAG_LONG, now_ms),
        "TotalBlocks": (TAG_INT, len(grid.cells)),
        "TotalVolume": (TAG_INT, volume),
        "RegionCount": (TAG_INT, 1),
        "EnclosingSize": (TAG_COMPOUND, {
            "x": (TAG_INT, size_x),
            "y": (TAG_INT, size_y),
            "z": (TAG_INT, size_z),
        }),
    }

    # Root compound
    root = {
        "Version": (TAG_INT, SCHEMA_VERSION),
        "SubVersion": (TAG_INT, 1),
        "MinecraftDataVersion": (TAG_INT, DATA_VERSION),
        "Metadata": (TAG_COMPOUND, metadata),
        "Regions": (TAG_COMPOUND, {
            region_name: (TAG_COMPOUND, region),
        }),
    }

    out_path = output.with_suffix(".litematic")
    write_nbt_file(str(out_path), "", root)
    return [out_path]


def _pack_block_states(
    grid: VoxelGrid,
    palette_map: dict[str, int],
    x0: int, y0: int, z0: int,
    size_x: int, size_y: int, size_z: int,
) -> list[int]:
    """Pack block indices into a long array using variable bit packing.

    Litematica stores blocks as packed longs where each block uses
    ceil(log2(palette_size)) bits.
    """
    palette_size = len(palette_map)
    if palette_size <= 1:
        bits_per_block = 1
    else:
        bits_per_block = max(2, (palette_size - 1).bit_length())

    volume = size_x * size_y * size_z
    blocks_per_long = 64 // bits_per_block
    num_longs = (volume + blocks_per_long - 1) // blocks_per_long
    mask = (1 << bits_per_block) - 1

    longs = [0] * num_longs

    for y in range(size_y):
        for z in range(size_z):
            for x in range(size_x):
                block = grid.get(x + x0, y + y0, z + z0, default="minecraft:air")
                if isinstance(block, int):
                    block = "minecraft:air"
                idx = palette_map.get(block, 0)

                bit_index = (y * size_z * size_x + z * size_x + x) * bits_per_block
                long_index = bit_index // 64
                bit_offset = bit_index % 64

                if long_index < num_longs:
                    longs[long_index] |= (idx & mask) << bit_offset
                    # Handle overflow into next long
                    if bit_offset + bits_per_block > 64 and long_index + 1 < num_longs:
                        overflow = bit_offset + bits_per_block - 64
                        longs[long_index + 1] |= (idx >> (bits_per_block - overflow)) & ((1 << overflow) - 1)

    # Convert to signed 64-bit longs for NBT
    return [v if v < (1 << 63) else v - (1 << 64) for v in longs]
